---
httpd:
  bind_address: "{{ jbcs_bind_address }}"
  listen_port: "{{ jbcs_listen_port }}"
  mod_cluster:
    enable: "{{ jbcs_mod_cluster_enable }}"
    port: "{{ jbcs_mod_cluster_port }}"
    require: "{{ jbcs_mod_cluster_require }}"
  home: "{{ jbcs_home }}"
  user:
    name: "{{ jbcs_user }}"
  group:
    name: "{{ jbcs_group }}"
    id: "{{ jbcs_group_id }}"